### PR TITLE
Fix file paths in constants

### LINKED ISSUE #17: File paths need to load from __FILE__
Loading this gem from another project results in a file not found because `config/temp...` etc are all relative to wherever we're loading stuff.

e.g.
https://github.com/richardwu/news_scraper/blob/master/lib/news_scraper/constants.rb#L3

this is an example of how we need to handle it: `File.expand_path('../config/...', __FILE__)`

### PR DESCRIPTION
**Pull request by jules2689**
fixes https://github.com/richardwu/news_scraper/issues/17

### CODE REVIEW

File: lib/news_scraper/constants.rb [hunk 1]
```diff
@@ -1,7 +1,7 @@
 module NewsScraper
   module Constants
-    TEMP_DIRS = YAML.load_file('config/temp_dirs.yml')
-    SCRAPE_PATTERN_FILEPATH = 'config/article_scrape_patterns.yml'.freeze
```
Comment (jules2689) [inline lib/news_scraper/constants.rb:4]: freeze isn't reallllly needed, and it makes overriding in tests difficult. I can't think of another way to override this otherwise

**Comment by jules2689** [comment]
cc @richardwu

**Comment by richardwu** [comment]
👍
